version: '3'

services:
  db-mycollection:
    image: 'postgres:latest'
    ports:
      - "5433:5432"
    container_name: db-mycollection
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mycollection_db

  my-collection:
    build: .
    ports:
      - "8081:8081"
    container_name: api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-mycollection:5432/mycollection_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db-mycollection
