server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycollection_db?&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true
      &serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true

  jpa:
    database: MYSQL
    show-sql: true

    properties:
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update