INSERT INTO public.artists (id,country,"name") VALUES
	 (1,'Sweden','Leviticus'),
	 (3,'Norway','Pagans Mind'),
	 (5,'United States','Cacophony'),
	 (6,'Germany','Axel Rudi Pell'),
	 (7,'Canada','Borealis'),
	 (8,'United States','The Human Abstract'),
	 (9,'United States','Impellitteri'),
	 (10,'United States','Further Seems Forever'),
	 (12,'United States','One Bad Pig'),
	 (13,'Italy','DGM');
INSERT INTO public.artists (id,country,"name") VALUES
	 (14,'Netherlands','Elegy'),
	 (15,'Netherlands','Textures'),
	 (16,'United States','Death'),
	 (17,'Brazil','Dark Avenger'),
	 (18,'Denmark','Pyramaze'),
	 (19,'Norway','Jorn'),
	 (11,'Italy','Thy Majestie'),
	 (20,'Brazil','Angra'),
	 (21,'United States','The Fall Of Troy'),
	 (22,'United States','Cyclone Temple');
INSERT INTO public.artists (id,country,"name") VALUES
	 (23,'United States','Believer'),
	 (24,'United States','Crimson Thorn'),
	 (25,'Australia','Mortification'),
	 (26,'United States','Prototype'),
	 (27,'England','Robert Plant'),
	 (28,'Brazil','Venus'),
	 (29,'Brazil','Symbols'),
	 (30,'United Kingdom','Whitesnake'),
	 (31,'Finland','Symfonia'),
	 (34,'Brazil','Shaman');
INSERT INTO public.artists (id,country,"name") VALUES
	 (35,'United States','Firehouse'),
	 (36,'United States','Sacred Warrior'),
	 (37,'United States','Pantera'),
	 (38,'United States','Stavesacre'),
	 (39,'Ukraine','Dying Blaze'),
	 (40,'Sweden','Skald in Veum'),
	 (41,'Brazil','Tito Falaschi'),
	 (42,'Sweden','Shadows of Paragon'),
	 (43,'United States','Spite of Opposition'),
	 (44,'United States','The Blamed');
INSERT INTO public.artists (id,country,"name") VALUES
	 (45,'United States','The Black Dahlia Murder'),
	 (46,'United States','Queensrÿche'),
	 (47,'Denmark','King Diamond'),
	 (48,'Sweden','Pain of Salvation'),
	 (49,'Sweden','Talisman'),
	 (50,'Norway','Antestor'),
	 (51,'United States','Living Sacrifice'),
	 (52,'United States','Magnitude 9'),
	 (53,'Sweden','Dionysus'),
	 (54,'Denmark','Beyond Twilight');
INSERT INTO public.artists (id,country,"name") VALUES
	 (55,'Brazil','Dynasty Of Metal'),
	 (56,'United States','Trouble'),
	 (57,'Czech Republic','Kreyson'),
	 (58,'Brazil','Dark Night'),
	 (59,'Germany','Seventh Avenue'),
	 (60,'United States','This Divided World'),
	 (61,'Australia','Paramaecium'),
	 (62,'Mexico','Lament'),
	 (63,'United States','Deliverance'),
	 (64,'United States','Dream Theater');
INSERT INTO public.artists (id,country,"name") VALUES
	 (65,'United States','Demonic Extinction'),
	 (66,'Brazil','Rarmagom'),
	 (67,'Brazil','Mitrium'),
	 (68,'United States','The Crucified'),
	 (69,'Sweden','Pantokrator'),
	 (70,'Finland','Immortal Souls'),
	 (71,'Netherlands','Morphia'),
	 (72,'United States','Saviour Machine'),
	 (73,'Canada','Sympathy'),
	 (74,'Norway','Vardøger');
INSERT INTO public.artists (id,country,"name") VALUES
	 (76,'United States','King James'),
	 (78,'Brazil','Edu Falaschi'),
	 (79,'Australia','Metanoia '),
	 (80,'United States','Becoming the Archetype'),
	 (81,'Sweden','Nocturnal Rites'),
	 (82,'Brazil','Berith'),
	 (83,'Brazil','Aquaria'),
	 (84,'Sweden','Atlas Losing Grip'),
	 (85,'United States','Redemption'),
	 (86,'Sweden','Crimson Moonlight');
INSERT INTO public.artists (id,country,"name") VALUES
	 (87,'Brazil','Sinistra'),
	 (88,'Brazil','Luis Mariutti'),
	 (106,'United States','Overcome'),
	 (107,'Brazil','Belica'),
	 (108,'Sweden','Starbreaker'),
	 (109,'Brazil','Charlie Brown Jr.'),
	 (110,'Brazil','Endless'),
	 (111,'United Kingdom','Slash'),
	 (112,'Brazil','Hazeroth'),
	 (113,'Brazil','Soulspell');
INSERT INTO public.artists (id,country,"name") VALUES
	 (114,'Brazil','Resgate'),
	 (115,'Sweden','The Flower Kings'),
	 (116,'United States','Steve Morse Band'),
	 (117,'Italy','Rhapsody'),
	 (118,'Brazil','Allegro'),
	 (119,'Italy','Genius - A Rock Opera'),
	 (120,'United States','Shadow Gallery'),
	 (121,'Brazil','Stauros'),
	 (122,'Brazil','Kiko Loureiro');
